# Generated by Django 3.0.2 on 2020-01-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(max_length=5, unique=True)),
                ('customer_name', models.CharField(max_length=10)),
                ('customer_email', models.CharField(max_length=10)),
            ],
        ),
    ]
